# Generated by Django 6.0.2 on 2026-02-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
