# Generated by Django 6.0.2 on 2026-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sisorigem_sisconfig_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sisconfig',
            name='chave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sisconfig',
            unique_together={('chave', 'origem')},
        ),
    ]
