# Generated by Django 6.0.2 on 2026-02-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sisconfig_chave_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='configuracao',
            unique_together={('empresa', 'parametro')},
        ),
    ]
