# Generated by Django 5.2.4 on 2026-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_pessoa_tipo_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
