# Generated by Django 5.2.4 on 2026-02-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_fk_cidade_estado'),
        ('finance', '0003_add_pessoa_localizacao_contato'),
    ]

    operations = [
        # Removemos os campos de texto antigos e criamos os FKs do zero,
        # sem tentar converter automaticamente valores existentes.
        migrations.RemoveField(
            model_name='pessoa',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='core.estado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='core.cidade'),
        ),
    ]
