# Generated by Django 6.0.2 on 2026-02-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_banco_id_alter_centroresultado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroresultado',
            name='centro_contabil',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='centroresultado',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='centroresultado',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', max_length=1),
        ),
    ]
