# Generated by Django 6.0.2 on 2026-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_centroresultado_centro_contabil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoconta',
            name='natureza',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='planoconta',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='planoconta',
            name='tipo',
            field=models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', max_length=1),
        ),
    ]
