# Generated by Django 6.0.2 on 2026-02-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_planoconta_natureza_planoconta_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoconta',
            name='conta_contabil',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
