# Generated by Django 6.0.2 on 2026-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_contapagar_competencia_contapagar_data_emissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='documento',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
