# Generated by Django 5.2.4 on 2026-02-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_add_juros_multa_conta_pagar_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='centro_resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.centroresultado'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.planoconta'),
        ),
    ]
