# Generated by Django 6.0.2 on 2026-02-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_banco_id_alter_centroresultado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
