# Generated by Django 6.0.2 on 2026-02-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_lancamento_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='baixa_conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.contapagarbaixa'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='baixa_conta_receber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='finance.contareceberbaixa'),
        ),
    ]
