# Generated by Django 6.0.2 on 2026-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_lancamento_baixa_conta_pagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceberbaixa',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contareceberbaixa',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
