# Generated by Django 6.0.2 on 2026-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
